name: build

on: [push]

jobs:
  build-executable:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-poetry-nox

      - name: Build `romt` executable
        run: poetry run nox -s build

      - uses: actions/upload-artifact@v4
        with:
          name: "dist-${{ matrix.os }}"
          path: dist/

  build-executable-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: "Dockerfile"
          tags: romt_build:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

      - name: Run docker to build for linux
        uses: ./.github/actions/run-docker/

      - uses: actions/upload-artifact@v4
        with:
          name: dist-ubuntu-latest
          path: "${{ github.workspace }}/dist/"
